### ISSUE TITLE
Transaction history improvements

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/MultiCurrencyWallet#2670]
# Problem

You dont see resulting balance
Transaction status is not obvious
You don't see pending transaction if someone initiataded a transfer

# Task

You need to make it look good.

1.  You need to  make resulting balance of transaction visible
![image](https://user-images.githubusercontent.com/22708849/79545717-d29bd100-8099-11ea-8d52-fcce3e5e8b7a.png)
It should be visible in  the currency of the current wallet.

2. The dollar (eur etc) amounts should be shown on hover.
When you hover over an amount  in BTC, you should see full amount  in btc without rounding, and its approximate equivalent in fiat currency.

3. If its a multisig account  and someone  initiated a transaction, and haven't cancelled it,  you need to  see  it in list of transaction with "requires signature" status. The resulting balance should not be affected, such transactions should be  clearly visible:
![image](https://user-images.githubusercontent.com/22708849/79548173-ad10c680-809d-11ea-86c0-0b22ec6d85e0.png)
The date will appear of initiation  of transaciton, but once confirmed, it should be sorted by date (or block) of first confirmation .

4. When  you click on transaciton you need to animate unfolding of 
 the transaction block right inside the  table of all transaction with more details.
    * transaction id
    * exact amount 
    * number  of confirmations
    * actions required (if any): cancel, sign, etc..
    * fees taken
    * fiat equivalents of amounts
    * etc..

Most importantly we need to fix issues with jumping balances and transactions not appearing in status bars..

# Purpose

Intuitiveness and usefulness.

# Area

frontend and some backend changes to make changes immediate. we  can't wait fo blockchain to swallow a transaction to display correct list of transaction including those that are pending
backend need to  cache whatever it  got from blockchain or from us to make sure it has the most recent list of pending, confirmed and unconfirmed transactions. so when you do reloads or go back and forth between screens you receive  always  the same list  of transactions unless there is some new comming in.

# Estimate time of implementation

1   month?

# Additional data

**Comment by vladiuz1** [comment]
![image](https://user-images.githubusercontent.com/22708849/79556390-af791d80-80a9-11ea-8127-15f80e9ece41.png)

Also good idea to add accounting-friendly number of significant digits and have the same number of digits after the "."

Less significant digits we can make gray.

monospace font family will make it so that digits with same  significance are on  equal level

**Comment by vladiuz1** [comment]
![dialogs-2](https://user-images.githubusercontent.com/22708849/79573082-b95d4980-80c6-11ea-8cca-b1192e8132d7.png)

Диалоги должны быть
* закрываемые (кнопкой и крестиком)
* иметь одинаковый look and feel. то есть быть в том  же месте и одинакового  стиля
* размывать ненужный фон (возможноо кроме баланса) и делать его не кликабельным
* всегда работать как t34

**Comment by vladiuz1** [comment]
It would be nicer if send dialogues was on 1 screen. without having to click

The source wallets would  be displayed in dropdown. by default - the last used wallet (for sending) or wallet with biggest balance in usd equivalent.

![send  dialogue](https://user-images.githubusercontent.com/22708849/79574990-b748ba00-80c9-11ea-95c5-0296667474a2.png)

![send dialogue](https://user-images.githubusercontent.com/22708849/79574719-3ee1f900-80c9-11ea-83ba-7212d53e5ae0.png)

**Comment by noxonsu** [comment]
по поводу транз требующих действия давайте по дизайну сделаем, просто не дошли до этого пока. но займемся поочереди 
![](https://screenshots.wpmix.net/chrome_kjf50ws3F6f0fg0BmQGWZb69I0EE6UwW.png)

**Comment by Pasha8914** [comment]
history table, invoice table, table from the currency page are the same data just with different filters

therefore, you need to rewrite these 3 components, to 1 common, which will be based on the history table, but add filters there that will be thrown by props


this leads to a decrease in the code, its greater comprehensibility and reduces the risk of crash


if you upload a list of transactions and put it in the store, you don’t have to unload this data every time while change route just filter (display data from the store and update it in the background)

**Comment by vladiuz1** [comment]
> Here is the designers vision of transactions which needs actions, let's take this as basic design
> ![](https://camo.githubusercontent.com/7cabf8738894094bd85f2c6e1575ad47c59d008d/68747470733a2f2f73637265656e73686f74732e77706d69782e6e65742f6368726f6d655f6b6a66353077733346366630666730426d5147575a62363949304545365577572e706e67)

Ok the designer didnt take into account the following:

https://user-images.githubusercontent.com/22708849/79560253-f36f2100-80af-11ea-8a7d-d613c19a8717.png

Also, the designer did  not change the resulting balance after  transaction, not good. Must be as I  asked.

I  know it looks nicer when there is no mono  fonts, and too many colors, but from the pro user point  imho,  its better to stress the important  part of the amounts.

**Comment by vladiuz1** [comment]
Строка  поиска в истории транзакций - это бомбейская идея

посмотрите как сделано у gitlab

![image](https://user-images.githubusercontent.com/22708849/79772509-d4cf8b00-8338-11ea-94db-5331e4de4be6.png)

Надо сделать что-то типа того, так-же легко удобно и логично

**Comment by noxonsu** [comment]
![invoice4](https://user-images.githubusercontent.com/22708849/79770146-af8d4d80-8335-11ea-9e56-3f27069876e4.png)

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/issues/2687#issuecomment-616097987
The confirmation screen can be universal for a few scenarios:
- [ ] Confirmation of simple wallet transaction
- [ ] Multisignature wallets, when the other pary signs the trasaction
- [ ] 2FA comfirmation.
Связанное ишью https://github.com/swaponline/MultiCurrencyWallet/issues/2625

**Comment by noxonsu** [comment]
# Transaction ledger service

If we make trnsaction ledger service on the backend with the functionality to save transactions on all stages, we need to remove the "requests" folder

![no-requests](https://user-images.githubusercontent.com/22708849/79725488-f8231780-82f1-11ea-9b22-8c8713446c01.png)

Instead, this will be a filter on regular transaction list:

![invoice-the-right-way](https://user-images.githubusercontent.com/22708849/79728253-4b976480-82f6-11ea-9c6c-6db18547f8f3.png)

And  the link of such page should be:

*  `https://swaponline.io/#/history?filter=tag:invoice`

And there should be notifications, also different types:
* Incomming invoices
* Incomming multisig transactions that require signatures
* New Incomming transactions to wallets

**Comment by noxonsu** [comment]
(decomposition https://github.com/swaponline/MultiCurrencyWallet/issues/2419 )
Unlike many other blockchain explorers, our must be more accounting-oriented, rather than blockchain oriented. This means, our transaction list must be more user-friendly to professionals who wish to view balances and transactions, rather than understand the blockchain details. This means that in the (5) transaction list we need to

- [ ]  display the date of transaction

- [ ]  amount of transaction (in currency of the wallet. e.g. btc)
- [ ]  balance (the new balance after the transaction was complete, or when it will be complete)
- [ ]  we need an easy way to convert the transaction amount to fiat currency amount (usd), so you can see your transactions in fiat representation, the exchange rate must be valid for the time when the transaction was complete, rather than current exchange rate. So if you sent 3 months ago 0.1 btc, you should see first of all the 0.1 btc, but also its important that it was approx $700 at the time of transaction. (there is no need to convert resulting balance after transaction to fiat amount, as its irrelevant)

- [ ]  We need to see current balance of the wallet in the currency of the wallet (BTC) as main focus, but there current balance should also be shown in preferred fiat currency (e.g. USD), with lighter accent.
- [ ]  pending transactions should not influence the current balance, and the balance after transaction field must be empty, it will only be shown after transaction is accepted, and the time of acceptance should be the sorting value.

**Comment by Noah-svg** [comment]
有点麻烦，我直接接入了优盾钱包，去中心化的，资产动向和操作日志一目了然，还可以余额一键归集
