### ISSUE TITLE
Add NEXT.coin support

### ISSUE THREAD

**Issue by iower** [swaponline/MultiCurrencyWallet#3309]
### Phase 1 `Example`

- [x] build node
- [x] example: get address balance
- [x] example: mnemonic -> address
- [x] example: get address utxos
- [x] example: create tx
- [x] example: publish tx, explorer observable tx
- [x] run NEXT.coin node + RPC-proxy on the server

### Phase 2 `Wallet`
- [x] Core: add NEXT
- [x] MCW: add NEXT (wallet, create address)
- [x] MCW: address balance
- [x] MCW: NEXT tx/rx test on mainnet (testnet is down)

### Phase 4 `Swap`
- [x] MCW: ETH-NEXT swap
