### ISSUE TITLE
TurboSwaps (alpha)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/MultiCurrencyWallet#3875]
Phases: [alpha](https://github.com/swaponline/MultiCurrencyWallet/issues/3875) -> [beta](https://github.com/swaponline/MultiCurrencyWallet/issues/4028)

---

##  Add second swap method against atomic swap 

for our whitelabels they request this flow:

1. only "whitelisted" market makers can perform it
2. taker start swap
3. taker sends crypto to maker directly (no atomic swap)
4. makers send crypto to taker 
5. done

> возможно стоит чуть поменять аритектуру, чтоб программист который делает этот обмен не погружался в многослойность атомик свапа

---

### Phase 1 "alpha" (demo: only eth<->btc, only internal addresses, only front-front)

- Preparations
	- [x] decomposited
- Terms
	- [x] Describe terms
- Front/...
	- [x] Create icon
- Front/Exchange
	- [x] Form: atomic/turbo switch
	- [x] my offers list: add icon-mark (+mobile layout)
	- [x] all offers list: add mark (+mobile layout)
- Front/AddOffer
	- [x] Add offer: atomic/turbo switch
- Front: Redirect after confirm
	- [x] router: simplify `links.swap`
	- [x] few pages: 2 different redirects (atomic page/turbo page)
- Front: New swap page
	- [x] UI sketch: 2sides2blockchains (+mobile layout)
	- [x] flow-depended state
	- [x] i18n
- Core flows
	- [x] Create flows maker/taker
	- [x] Use Flow state `src/core/swap.swap/Flow.ts` as parent class
	- [x] fresh refacts compitability (was rewrited parallelly)
	- [x] flows maker/taker, min algo
	- [x] real send BTC (only front)
	- [x] real send ETH (only front)
- Additional
	- [x] fix offer sharing (highlight)
