### ISSUE TITLE
Customization request: conversation/93

### ISSUE THREAD

**Issue by VitaliyShulik** [swaponline/MultiCurrencyWallet#5027]
- [x] We have HTML start modal, need to add an option in the app to display it and after clicking on the "Create Wallet" show a modal screen with saving seed phrase (12 words), then display all wallets added in the app as you want. #5035

Develop a modal window with 2 tabs where:
- [x] users can add tokens via contract address (also there is a dropdown with the select network in input) #5029 
- [x] search tokens by name (use [the CoinGecko API](https://www.coingecko.com/en/api/documentation)), it will work only with tokens that have contract addresses in one's of our supported EVM network. #5032 

Add two EVM chains:
- [x] Fanton - #5028 
- [x] Avax - #5033

Deadline - March 10
